name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up GitHub Pages action for deployment
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Target branch for GitHub Pages
          folder: .  # Folder to deploy (use build folder if your code is built in one)
          token: ${{ secrets.GITHUB_TOKEN }}  # Token to allow deployment from GitHub Actions
